# Generated by Django 2.0.9 on 2018-12-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.IntegerField()),
                ('categoria_producto', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.TextField(blank=True)),
                ('precio_producto', models.IntegerField()),
                ('imagen_producto', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
    ]
