# Generated by Django 2.0.9 on 2018-12-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.IntegerField()),
                ('comentario_oferta', models.TextField(blank=True)),
            ],
        ),
    ]
