# Generated by Django 2.0.9 on 2018-12-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
        ('venta', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='oferta',
            field=models.ManyToManyField(to='oferta.Oferta'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='venta',
            field=models.ManyToManyField(to='venta.Venta'),
        ),
    ]
