# Generated by Django 2.0.9 on 2018-12-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_vendedor', models.CharField(max_length=20)),
                ('nombre_vendedor', models.CharField(max_length=50)),
                ('apellido_vendedor', models.CharField(max_length=100)),
            ],
        ),
    ]
