# Generated by Django 2.0.9 on 2018-12-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
        ('tienda', '0002_auto_20181210_1305'),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='tienda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.Tienda'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='venta',
            field=models.ManyToManyField(to='venta.Venta'),
        ),
    ]
